### ISSUE TITLE
Update integration information for Gradle in Getting Start section

### ISSUE THREAD

**Issue by filipedelimabrito** [ktlint/ktlint.github.io#3]
The information about how integrate Ktlint via Gradle from the [website](https://ktlint.github.io/#getting-started) differs about how it should be done from the [README.md](https://github.com/shyiko/ktlint#-with-gradle) file. While from the first we see that we should declare `mavenCentral()` in the `repositories {} block` the second says the we need to use ` jcenter()`.

**Comment by shyiko** [comment]
@filipedelimabrito Thank you for pointing it out. I'll make sure to address this as part of https://github.com/shyiko/ktlint/issues/115.

**Comment by shyiko** [comment]
Gradle section updated.
