### ISSUE TITLE
Website out of date regarding parameter list rule?

### ISSUE THREAD

**Issue by jtietema** [ktlint/ktlint.github.io#4]
Hi I downloaded the latest ktlint 0.28.0 and it seems the following rule works differently then explained on the website: https://github.com/ktlint/ktlint.github.io/blob/master/index.html#L313 it seems the "still OK but not preferred" way is no longer OK. Is that correct?

**Comment by shyiko** [comment]
Thanks, @jtietema. Updated to match https://kotlinlang.org/docs/reference/coding-conventions.html#class-header-formatting.
